mgmtsystem/openstack.py

self is HTTPClient there. As I found no simple way to pass logger there
let's skip logging for now

openstack: self.logger is not available in _request_timeout_handler

---

mgmtsystem/scvmm.py

Added Install virtual guest services to appliance after creation prior to power on to fix missing appliance IP address.

[FIX] Configure Guest Services on new VM prior to power on

---

mgmtsystem/scvmm.py

* the stop action may fail sometimes, based on the
state of the vm. this can be handled as execption
and execute delete_vm in finally (this is works with
-Force option).

Execute scvmm delete_vm in finally block.

---

mgmtsystem/base.py
mgmtsystem/openstack.py

So far only openstack as I could not figure out the others yet.
This should help when Sprout happens to lose an appliance due to some network issue or something. Sprout will store some metadata that will enable full object recovery.

VM metadata - Base + Openstack

---

mgmtsystem/azure.py

This isn't perfect, but it should fix the PRT issues surrounding 2977.  What it replaces didn't work at all after the all the credentials changes.

FIX - Synced up Azure Mgmt System init with AzureProvider

---

mgmtsystem/hawkular.py
tests/test_hawkular.py

Recently there is big change on Hawkular-inventory API, Current version of `mgmtsyatem/hawkular.py` is using `deprecated` version of inventory API. In this PR removed all `deprecated` API's of inventory and added support for new API's
Other changes,
- Class name `Path` changed to `CanonicalPath`
- Added `to_string` property in `CanonicalPath`
- Changes in `CanonicalPath`
* Earlier it was accassable like `path.feed`, `path.tenant`, etc.
* path having only Id's so it has been changed as `path.feed_id`, `path.tenant_id`, `path.resource_id`, etc. All path elements ends with `_id`. For more details refer `CanonicalPath` class
- Variable `tenant_id` added, default `tenant_id` is `hawkular`
- Following `functions` are renamed
* `_pup_inv_status` >> `_put_inv_status`
* `edit_resource_data` >> …

Upgraded hawkular inventory API version to 0.17.1.Final

---

README.rst

Some links on `README.rst` refers our old repository location(`RedHatQE/mgmtsystem`)

fixed broken links in README file

---

mgmtsystem/hawkular.py
mgmtsystem/rest_client.py
requirements.txt

Adding support for hawkular metrics query functions
Supports for metrics types
- `availability`
- `gauges`
- `counter`
- `status_alerts` - Returns `alerts` service status
- `status_inventory` - Returns `inventory` service status
- `status_metrics` - Returns `metrics` service status
- `status` - Returns all services status
- `list_metric_definition` - returns list of all metric definitions
- `list_metric_availability_definition` - returns list of all `availability` metric definitions
- `list_metric_gauge_definition` - returns list of all `gauge` metric definitions
- `list_metric_counter_definition` - returns list of all `counter` metric definitions
- `list_metric_availability_feed` - Returns list of availability metrics for a feed
- `list_metric_availability_server` - Returns list of …

Adding hawkular metrics query functions

---

mgmtsystem/rhevm.py

The endpoint is not always `/api` ... Therefore I added a possibility to specify a custom api endpoint.

RHEV: Custom API endpoint

---

mgmtsystem/rhevm.py

the rhevm api uri needs to include 'ovirt-engine' for version 4.0. so the uri would look like: http://rhevmip/ovirt-engine/api before it used to be http://rhevmip/api  
* appended 'ovirt-engine' to rhevm api uri.

update rhevm api uri to support 4.0

---

mgmtsystem/hawkular.py
mgmtsystem/websocket_client.py
requirements.txt
tests/test_hawkular.py

* Current `hawkula-wrapanapi` functions are growing day by day. Which leads complications on maintenance as well as produces difficulty on usability. To avoid this issue we have created sub classes for each hawkular services. Now it will be easily to manage/usable.
```
from mgmtsystem.hawkular import Hawkular
hwk = Hawkular(hostname="hawkular.redhat.com", port="8080", username="jdoe", password="password")
hwk.list_server()
hwk.list_event()
hwk.status_alerts()
hwk.list_metric_availability_server()
hwk.add_jdbc_driver()
etc.,
```
```
from mgmtsystem.hawkular import Hawkular
hwk = Hawkular(hostname="jee-hawkular.bc.jonqe.lab.eng.bos.redhat.com", port="8080", username="jdoe", password="password")
hwk.inventory.list_server()
hwk.alert.list_event()
hwk.alert.status() …
```

Restructured hawkular services api to sub classes, added support for hawkular operations and added generic web socket client

---

mgmtsystem/ec2.py

after today's update all test are failing as length of instance_id is now 19 symbols

fix to fit recent update on AWS EC2

---

mgmtsystem/hawkular.py

With this PR we add metric data to hawkular metric service/server.
New functions:
* `add_availability_feed`
* `add_availability_server`
* `add_availability_deployment`
* `add_gauge_server`
* `add_gauge_datasource`
* `add_counter_server`
* `add_counter_deployment`
* `add_string`
* `add_gauge`
* `add_counter`
* `add_availability`
Usage:
```
from mgmtsystem.hawkular import Hawkular
from mgmtsystem.hawkular import MetricEnum
from mgmtsystem.hawkular import MetricEnumGauge
from mgmtsystem.hawkular import MetricEnumCounter
hwk = Hawkular(hostname="hawkular-service-hostname", port="8080", username="jdoe", password="password")
_data = [] 
_data.append({'timestamp': 1473782555308, 'values': 21})
hwk.metric.add_counter_deployment(feed_id='ebf0ce66-0278-4d96-b9ec-4e4d42926dbe', server_id='Local', …
```

Added API support to add data on hawkular metrics server

---

mgmtsystem/openstack.py
mgmtsystem/virtualcenter.py

Found another name for a flavor for osp provisioning, vmw needed to add
kwargs to ignore extra parameters being passed to the template that we
not needed.

add some deploy_template flexibilty for vmw and osp

---

mgmtsystem/google.py

* get_ip_address() does not return the correct value in the existing implementation, changed it to fetch
the external_ip which could be used to connect the vm remotely.

Fix get_ip address for gce instance.

---

mgmtsystem/virtualcenter.py

* "bootTime" attribute is not always available in vm.runtime, we can fetch uptimSeconds from summary and convert that to vm_creationtime the way boottime used to give us. Since this is added to Except block, on first attempt try to get   boottime, get uptimSeconds otherwise.

Update virtualcenter vm creation time method.

---

mgmtsystem/ec2.py

* this method returns the instance type of the specified instance.
e.g. m1.medium, m3.medium

Added vm_type method to ec2.

---

mgmtsystem/google.py

* when ssh public key is specified, deploy gce instance with ssh-key metadata. ssh key is important to access gce instance, use private key to establish ssh connection.

deploy gce instances with ssh public key, when specified.

---

mgmtsystem/openstack_infra.py
requirements.txt

Querying via noa does not show the inactive nodes, so Ironic is required.
Example:
```
In [1]: from utils.providers import get_mgmt
In [2]: p = get_mgmt('provider key')
In [3]: p.list_node()
Out[3]: 
[Node(uuid=u'4ff82be7-be40-48c7-81ea-63dc059eb7d3', name=None, power_state=u'power off', provision_state=u'available'),
Node(uuid=u'607cc79c-5d30-42c4-bd76-e723d510e7a2', name=u'overcloud-controller-0', power_state=u'power on', provision_state=u'active'),
Node(uuid=u'694b9a1a-b687-44e6-8c73-67982b8c4317', name=u'overcloud-compute-0', power_state=u'power on', provision_state=u'active')]
```
The first entry is a node that cannot be queried via nova because it is not "plugged in" so Nova does not see it.
Required for @rrasouli

Added ability to query OSP nodes via Ironic

---

mgmtsystem/rest_client.py

I am not sure why it suddenly started failing, but this fixes it.

Fix Invalid auth object when it is unicode.

---

mgmtsystem/scvmm.py

I guess I misunderstood the previous request.  So now, instead of either parameter or yaml, it now uses either the parameter of the template default values.
I tested with every possible combination using scripts/clone_template.py

[RFR]Changed deploy_template to use default cpu ram unless passed by param

---

mgmtsystem/ec2.py

Unassociated EIPs are only these which are not associated to network interface.

Added get unused ENIs and fixed get unassociated EIPs

---

mgmtsystem/azure.py

There is no force flag for this call
Remove-AzureRmResourceGroupDeployment : A parameter cannot be found that matches parameter name 'Force'.
At line:4 char:107
+ ... urceGroupName Automation -DeploymentName $stack.DeploymentName -Force

[RFR]Removed non-existing -Force parameters

---

wrapanapi/scvmm.py

Some VMs in extreme error conditions were not being deleted in cleanup.  By adding the -Force flag, like in delete_template, this will remove even the VMs which are in an error condition.

[RFR]Force VM delete to catch weird errors

---

wrapanapi/virtualcenter.py

In the clone_vm method of the vSphere class, it was not expecting None when a VM doesn't exist. Changed it to expect a None.

[1LP][RFR] Fix an issue with clone_vm not expecting None

---

wrapanapi/virtualcenter.py

clone_vm was using _get_obj() for getting a VM which simply returns None if the object doesn't exist. Changed it to use _get_vm() so that an exception is raised. Also just tighten up the logic in does_vm_exist() a little.

[1LP][RFR] Fix an issue with non-existant VMs being handled incorrectly

---

wrapanapi/virtualcenter.py

This fixes some issues with logging of task error messages from the vSphere API, as seen in #147.

Fix the error logging for once and for all

---

wrapanapi/virtualcenter.py

vm.config.datastoreUrl returns an object, use \_\_getattribute\_\_ instead
of \_\_getitem\_\_
Also vm_status was returning a vim.VirtualMachine.PowerState object, return a string instead. Although its a wrapper for string, it breaks threaded applications that are trying to pickle some of these values.

[RFR] Update virtualcenter.get_vm_datastore_path and vm_status

---

wrapanapi/azure.py
wrapanapi/exceptions.py
wrapanapi/google.py
wrapanapi/openstack.py
wrapanapi/rhevm.py
wrapanapi/scvmm.py
wrapanapi/virtualcenter.py

Complete re-write of virtualcenter.vm_creation_time, don't return the uptime as vm_creation_time.
Parse vm events for a deployment/creation event
Otherwise standardize other modules to return a localized datetime object for vm_creation_time.
Add in some exception raising for azure/scvmm where the winrm crap blows up unexpectedly and you end up with empty lists for dates, and obscure exceptions otherwise.
The other classes are actually using API's and fail reasonably when the queried value isn't available.
Organized the imports, which makes the diff a little messy. :dealwithit:
FIXES RHCFQE-3262

[RFR] Standardize vm_creation_time

---

wrapanapi/openstack.py

creation_time is tznaive since python doesn't parse single Z as a
timezone.
timezone string includes 'Z', so we know its UTC if it was matched, make
the return datetime object tzaware by using replace() instead of
astimezone - which required a tzaware object in the first place.
Tested against CFME QE's 'rhos7-ga' provider.  Potential for more updates as we adopt more recent openstack environments.

[RFR] Update openstack.vm_creation_time

---

requirements.txt
wrapanapi/__init__.py
wrapanapi/containers/__init__.py
wrapanapi/containers/container.py
wrapanapi/containers/deployment_config.py
wrapanapi/containers/image.py
wrapanapi/containers/image_registry.py
wrapanapi/containers/node.py
wrapanapi/containers/pod.py
wrapanapi/containers/project.py
wrapanapi/containers/providers/kubernetes.py
wrapanapi/containers/providers/openshift.py
wrapanapi/containers/replicator.py
wrapanapi/containers/route.py
wrapanapi/containers/service.py
wrapanapi/containers/template.py
wrapanapi/containers/volume.py
wrapanapi/exceptions.py
wrapanapi/rest_client.py

Extend containers providers functionality.
- Created package wrapanapi.containers which includes openshift, kuberenetes and containers resources.
- Each container resource inherit wrapanapi.containers.ContainersResourceBase which provide the functionality to access the object API (GET/POST/PATCH/DELETE functions), the purpose is to provide mgmt entry for each container [object in integration_tests](https://github.com/ManageIQ/integration_tests/tree/master/cfme/containers).
- Added tests/test_openshift.py which tests all the required components.
- This commit is the start point for many other functionalities that required for containers provider REST-API which will take place later.

[RFR] Container Management Extensions

---

wrapanapi/azure.py

The datetime string requested from azure had 24hr time and AM/PM, which
broke dateutil.parser.parse
Tested locally using ManageIQ/Integration_tests/scripts/cleanup_old_vms, which calls vm_creation_time against all the VM's on the provider.

[RFR] Update azure.vm_creation_time, parseable datetime

---

wrapanapi/ec2.py

Adding this parameter resolved the region_name exceptions observed when using this module in CFME QE CI environments.

[RFR] Update ec2.init, set region_name in sns_connection

---

tests/test_openshift.py
wrapanapi/containers/image.py
wrapanapi/containers/providers/kubernetes.py

- Added openshift tests (tests/test_openshift.py)
- Option to run tests with both mock provider and real provider, default is mock.
- Fix image info parsing which was problematic in case we had more than one ':' in the image name. (happens when we have tag, in this case we have 2, one for the ID and one for the tag)

[RFR] Added openshift tests + Minor fixes in image info parsing

---

wrapanapi/rhevm.py

API requests against rhv41 provider were resulting in empty results (`list_vm`) because of the filter kwarg setting.
At some point we'll need to migrate the entire module to ovirt-engine-sdk-python 4.1.6+, but not yet.

[RFR] Update rhevm api kwargs, <4.0 vs >4.0

---

wrapanapi/base.py
wrapanapi/google.py

Support filtering by object's zone in all_vms, pass by_zone=True in
list_vm method
This means list_vm will now only list the VMs that are in the object's
zone. It should have been doing this all along, but has been returning
an unfiltered list of all instances in all regions
FIXES #195 
Tested both `list_vm()` and `all_vms()` against gce_central provider config from CFME QE. This was a GCE provider with zone of asia-east1-a. Was able to cleanly filter or get all VMs in the account.
Also modified `base.get_vm_guid` to call list_vm instead of all_vms

[RFR] Update google.all_vms, add by_zone option

---

wrapanapi/msazure.py

Don't create the client objects in `__init__`
This allows for changing attributes after the object is created.
Related to #204 where @lkhomenk  is enhancing azure cleanup.
This change will allow for easier instantiation and modification of the AzureSystem object within the context of cleanup and generation of the AzureSystem object from YAML definitions of providers.
If I have a provider, but don't yet have subscription IDs, with this design I can create an AzureSystem object, query the subscription ID's available, and then set one.

[RFR] Update azure properties, use cached_property

---

requirements.txt
wrapanapi/vcloud.py

With this commit we implement the first version of vcloud manager that is able to obtain following counts via vcloud API:
- num_availability_zone (i.e. number of vdcs)
- num_orchestration_stack (i.e. number of vapps)
- num_vm

[RFR] Implement wrapanapi class for VMware Cloud

---

wrapanapi/containers/providers/rhkubernetes.py

Fixes for the list_container_groups and list_service methods for CMQE. 
Manual testing:
```
In [2]: mgmt = juwatts.mgmt
In [3]: mgmt
Out[3]: <wrapanapi.containers.providers.openshift.Openshift at 0x7f8a415e6ed0>
In [8]: pods = mgmt.list_container_group()
In [9]: pods
Out[9]: 
[<Pod name="docker-registry-1-gjjgs" namespace="default">,
<Pod name="nationalparks-katacoda-1-build" namespace="default">,
<Pod name="nationalparks-katacoda-2-build" namespace="default">,
<Pod name="registry-console-1-xmrr5" namespace="default">,
<Pod name="router-2-lk4nd" namespace="default">,
<Pod name="router-2-nwdg9" namespace="default">,
<Pod name="logging-curator-1-jk429" namespace="logging">,
<Pod name="logging-es-data-master-z2yths8j-1-d6bf5" namespace="logging">,
<Pod name="logging-fluentd-2q9jm" …
```

[RFR] Fix list_services and list_container_groups

---

requirements.txt

Force update of azure-storage-common >=1.1.0
Pip is installing azure 3.0, which needs azure-storage-common 1.1.0. The azure-storage-common 0.37.1 package was satisfying azure >=2.0, and being installed from cache.
This forces install of azure 3.0 dependent packages.

Update azure version to >=3.0.0

---

wrapanapi/msazure.py

This fixes test_provider_crud for azure
`_stats_available` was  getting from info:
`num_vms` - we got from all Regions
`num_templates` - we got all vhds from container that is not used by CFME templates + we were skipping Private Images
Needs - MR 450

[RFR]few fixes for list_vm / list_templates

---

requirements.txt

It turned out that newest version (0.4.3) is incompatible. So, I add a version freeze for a while.

[RFR] openshift client version freeze

---

wrapanapi/ec2.py

If a stack doesn't exist an exception can be raised. This PR makes better handling of such exceptions.

[1LP][RFR] Better error handling for stack_exist() method in ec2.py

---

wrapanapi/google.py

`can_suspend` is currently returning 'True' but the `is_vm_suspended()` method raises an exception due to not being implemented.

[1LP][RFR] Set can_suspend to false for GCE until suspend methods are implemented

---

wrapanapi/msazure.py

The full path for provisioning templates was not being utilized. This changes it so we don't strip the full path name when it is defined. This makes it easier to take the full image path after provisioning tools like packer build the image and put it straight into the YAMLs.
So a config like this would work now:
```yaml
templates:
small_template:
name: 'Microsoft.Compute/Images/fedora-tmpl-sm.vhd'
creds: cloudqe_azure_instance
big_template:
name: 'Microsoft.Compute/Images/tmpl-osDisk.vhd'
creds: cloudqe_azure_instance
```
There should be no impact with this change to azure tests on the current setup because the small template name's file path is currently defined as 'fedora-tmpl-sm.vhd' and that is also where it lives in the cloud blob storage.

[1LP][RFR] Don't strip image path

---

requirements.txt
wrapanapi/ec2.py

We need retries implemented to be able to handle rate exceeded from aws.
In this PR I reworked delete_stack from boto2 to boto3
PR(https://github.com/ManageIQ/integration_tests/pull/6850) relies on this PR.
Tested.

Boto3 for cloudformation stacks 

---

wrapanapi/ec2.py

As wrapanapi doesn't support multiple VM operations on ec2. it would be nice to forbid duplicated names during creation

[RFR]banning duplicated names on ec2

---

wrapanapi/nuage.py

With this commit we prevent JSON parsing in case of empty response body, because it fails otherwise. We now return empty list in such cases.

[RFR] Handle empty response in Nuage API calls

---

wrapanapi/lenovo.py

This PR updates the _list_servers_ method to gather a list of nodes/servers from all cabinets instead of just the first cabinet. Also, the _get_server_memory_ method was updated to return the amount of memory in bytes, so it matches the value that is displayed in the UI.

[1LP][RFR] Reimplement list_servers and fix get_server_memory in lenovo.py

---

wrapanapi/scvmm.py

Allows a port and scheme (http/https) to be passed in to SCVMMSystem for the WinRM connection. Defaults to http/5985
Tested with both the new and old scvmm environments. The new env will have a winrm_port and winrm_scheme kwarg defined in the cfme-qe-yamls provider data.

[RFR] Winrm ssl

---

wrapanapi/containers/providers/rhopenshift.py

Some jenkins template tester jobs fail on destroy vm step though vm is deleted. It seems 2 min sometimes isn't enough. I increased value to 5 min

[RFR] 2 min sometimes isn't enough to delete vm

---

wrapanapi/scvmm.py

This command was failing on the new VMM deployments likely because LOCAL\Administrator didn't have proper access. Using the domain account is probably the "better" way to go here.

[RFR] Use domain account when enabling guest services

---

wrapanapi/containers/providers/rhopenshift.py

openshift provider becomes slow under high load. so, default waits should be increased in order to work properly in sprout

[RFR] increase default wait_for values for openshift

---

wrapanapi/entities/vm.py
wrapanapi/systems/base.py

Fixes errors like this: `Exception: GoogleCloudSystem has empty self._stats_available dictionary`

[RFR] Don't overwrite class var

---

wrapanapi/entities/vm.py
wrapanapi/systems/google.py

Some tests were hitting a TimedOutError waiting for the VM to delete. I'm not hitting this in local tests, my only guess is that the VM was taking a long time to go from "STOPPING" state to completely deleted. 
Also, we were querying for the VM twice (once for self.exists, once again for self.state) -- this will just use `self.state` "to hit 2 birds w/ one stone"

[RFR] Increase gce delete timeout, change the logic in vm.exists so we don't query for VM twice

---

wrapanapi/systems/virtualcenter.py

just return None, as is expected behavior of the callers when the item doesn't exist

Handle ManageObjectNotFound in vcenter on object filter

---

wrapanapi/systems/container/rhopenshift.py

Update method list_image_id to return a list of unique image ids.
No PRT test.
Will be implemented as part of new PR [Update Container test project dashboard according to wrapanapi changes #7400](https://github.com/ManageIQ/integration_tests/pull/7400)
Manual Testing:
My test provider has 6 images on namespace\project 'test-project-dashboard',
But only 4 unique images.
example before wrapanapi change, get list with 6 images, same images are on bold:
ocp_37_prom.mgmt.list_image_id(namespace='test-project-dashboard')
Out[1]: 
[**'docker-pullable://registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat7-openshift@sha256:81daf7f932be28e8b3d948d86ce6f175a98124ba54dbb40c3609317353f93753'**,
**'docker-pullable://registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat7-openshift@s …

[RFR] Update containers rhopenshift list_image_id to return unique list of image ids

---

wrapanapi/systems/container/rhopenshift.py

Update containers rhopenshift openshift method:
- list_image_registry - return only registry name.
No PRT test, please see the following comment

[RFR] Update containers rhopenshift openshift list_image_registry to return only registry name

---

wrapanapi/systems/container/rhopenshift.py

1. makes deploy_template save config map with all tags and urls. It is necessary for ansible pod deployment in 5.10
2. splits mappings for version 5.8 and 5.9
3. adds method to obtain ansible tag

[RFR] initial support of saving config map with urls within project

---

wrapanapi/systems/virtualcenter.py

This upate is made based on 
https://github.com/vmware/pyvmomi/issues/694#issuecomment-400124246
and https://kb.vmware.com/s/article/2145796
Tested to work against vSphere 5.5/6.0/6.5/6.7 using calling methods below:
```
provider.mgmt.list_cluster()
provider.mgmt.list_vms()
provider.mgmt.list_datastore()
provider.mgmt.list_templates()
provider.mgmt.list_host()
```

[RFR] Changing way to create the ssl context as TLSv1.0 is disabled by VMware for vSphere 6.7

---

wrapanapi/systems/lenovo.py

if ``device`` has no key ``class`` it throws AttributeError for the method ``.lower()``.
this PR fixes it.

[RFR] fix NoneType in LenovoSystem

---

wrapanapi/systems/nuage.py

Add `list_cloud_tenants` and `list_network_routers` function that returns enterprises and domains, which are used to test number of cloud tenants and network routers. Previous `list_network_groups`, that called `/enterprise` API, was removed since it was obsolete.

[RFR] Implement list tenants and routers

---

wrapanapi/systems/rhevm.py

VM is often assigned an IPv6 link-local address way before
IPv6 global or IPv4 address.
Subsequent attempt to SSH to such machine then fails, unless we pick
the right address. This is a problem for example in ssa tests:
https://github.com/ManageIQ/integration_tests/blob/6b09a70d1463ad410c09e46fc27bd0eedb21653f/cfme/tests/cloud_infra_common/test_vm_instance_analysis.py#L257
In such case, waiting for IP is pointless, because in the first call is returned the 
link-local IP address.
In this PR, I changed the the vm ip property to by default return None
until IPv4 address is found in the assigned ip addresses.

[RFR] Make ip property return IPv4 address (RHV)

---

wrapanapi/__init__.py
wrapanapi/systems/__init__.py
wrapanapi/systems/redfish.py

This commit contains the bare minimum support for the API to be
used by the integration tests, which test the Redfish type of
the [physical infrastructure providers](https://github.com/ManageIQ/manageiq-providers-redfish).
The API implementation currently does not yet make any actual
Redfish client calls. Instead, it encodes the state as we expect
it from the [mock-up server](https://github.com/xlab-si/redfish-recordings).
In this commit, we only validate the number of servers disovered
by the provider.
/cc @gberginc @tadeboro

Add initial support for Redfish physical provider

---

wrapanapi/systems/container/rhopenshift.py

It turned out that sprout is much closer to openshift server and sends requests when some data isn't ready yet. openshift client returns None instead of empty array in such case. So, that method should catch such exception.

[RFR] fix of external ip extract method for quick environments

---

wrapanapi/entities/vm.py

This PR fixes scenarios where method ensure_state(VmState.STOPPED) is called:
https://github.com/ManageIQ/wrapanapi/blob/ad764e7e5a50773a12e614f5a4f05e83d8e2bd93/wrapanapi/systems/rhevm.py#L182
If I understand correctly, the problem is that this method is sometimes called when the VM to be deleted is in state VmState.STARTING. Subsequently, this call doesn't wait for the VM to get to  VmState.RUNNIG and the self.stop action is called right away:
https://github.com/ManageIQ/wrapanapi/blob/ad764e7e5a50773a12e614f5a4f05e83d8e2bd93/wrapanapi/entities/vm.py#L282
The result is then the following exception:
Error: Fault reason is "Operation Failed". Fault detail is "[Cannot remove VM. VM is running.]". HTTP response code is 409.
This can be observed for example in PRT in test cases that remove …

[RFR] Fix ensure_state fail when VM is in starting state

---

wrapanapi/entities/vm.py

Locally resolving the py3 compatibility issue when trying to use wrapanapi.

Remove basestring for py3 compatibility

---

requirements.txt
wrapanapi/entities/__init__.py
wrapanapi/entities/server.py
wrapanapi/systems/redfish.py

With this PR we replace the hard-coded value for the stat check with that obtained by the Redfish provider's implementation now uses [the Redfish API client](https://pypi.org/project/redfish-client/).
We initiated a new entity `Server` and contributed `ServerStats` enum, which `RedfishServer` implements with its API specifics. The `RedfishSystem` is implemented such that it can be used both for testing stats at the provider level and for a selected physical server instance.
~~Depends on https://github.com/ManageIQ/integration_tests/pull/7735 and https://github.com/ManageIQ/wrapanapi/pull/331.~~
/cc @tadeboro, @miha-plesko

[RFR] Adds Redfish API client

---

wrapanapi/systems/ec2.py

Priority should be like this:
tagged name > ami name > ami id(shouldn't happen as ami name is required)

Tagged name should have higher priority than AMI name

---

wrapanapi/systems/nuage.py

Nuage CRUD test was failing in case any entity named 'BackHaul' existed on Nuage server due to entity counts mismatch. That's because CloudForms explicitly won't inventory such entities while current integration test expects them present.
/cc @miha-plesko

[RFR] Filter out Backhaul subnet names the same way CloudForms does

---

wrapanapi/entities/__init__.py
wrapanapi/entities/base.py
wrapanapi/entities/instance.py
wrapanapi/entities/physical_container.py
wrapanapi/entities/server.py
wrapanapi/entities/stack.py
wrapanapi/entities/template.py
wrapanapi/entities/vm.py
wrapanapi/systems/base.py
wrapanapi/systems/redfish.py

We expand the Redfish API implementation to include retrieval and inspection of Chassis resources.
This PR introduces class `RedfishResource` that abstracts Redfish entities such as `Systems`, `Chassis` or `EventService`.
In the context of physical infrastructure, servers normally reside in one or more nested enclosures such as chassis or racks. This new entity serves as a reporesentation of these physical containers. Not to be confused by container virtualisation technology.
The Redfish API now supports retrieving Chassis resources, which are general chassis entities. It also provides helper methods for retrieving physical racks, which are a special type of Chassis. The Redfish racks currently support getting the name of the rack. The Redfish chassis support obtaining chassis name and …

[RFR] Add API for Redfish chassis navigation

---

wrapanapi/systems/container/rhopenshift.py

Sometimes vms are broken and cannot be stopped. We anyway need to try to remove them

[RFR] remove broken vms in openshift

---

wrapanapi/systems/rhevm.py
wrapanapi/systems/scvmm.py

Some sprout tasks fail during vm hardware configuration update because get_vm_hardware methods return memory in bytes instead of MB

[RFR] wrongly updated method during wrapanapi 3.0 conversion

---

requirements.txt
wrapanapi/systems/rhevm.py

Fixed [async](https://docs.python.org/3/reference/compound_stmts.html#the-async-with-statement). Remove use of `async` keyword. more description refer https://github.com/ManageIQ/wrapanapi/issues/354
on 17 ovirt released so best to move now. 
FIXES #354

async as reserved keyworkd in py3.7+

---

wrapanapi/systems/msazure.py

get rid of azure size enum in favor of using value instead of name everywhere

[RFR] tests and wrapanapi should use size value instead of name everywhere

---

wrapanapi/systems/google.py

Default the service account 'type' field to `'service_account'` if its not passed into the constructor along with the service_account creds dict.

[RFR] Update gce, set service_account type by default

---

wrapanapi/exceptions.py
wrapanapi/systems/virtualcenter.py

Signed-off-by: Nikhil Dhandre <ndhandre@redhat.com>

[RFR][VirtualCenter] Added method set hot add for cpu and memory

---

wrapanapi/systems/ec2.py

As we want to move to python3 we have to move from boto to boto3.
With this PR elb_connection for ec2 will use boto3
Also the rest of EC2System and EC2Image, EC2Instance and EC2CloudFormation classes are reworked.
Tested, but found some issues - most of them were already there in boto.
For integration_tests I prepared PR which reflects these changes: https://github.com/ManageIQ/integration_tests/pull/8535

[1LP][RFR] ec2.py module changed from boto to boto3

---

wrapanapi/exceptions.py
wrapanapi/systems/virtualcenter.py

This PR introduces the ability to clone or relocate a VM/template on a datastore cluster. 
For deploying on a datastore, `CloneVM_Task` is replaced by `RecommandedDatastores` and `ApplyStorageDrsRecommendation_Task`. This is because `CloneVm_Task` forces you to specify the specific datastore for your new VM. 
Testing:
You can either specify a datastore object (vim.Datastore), datastore cluster object (vim.StoragePod), or the name (string) of the datastore or datastore cluster.
If no datastore is provided,  it is picked in the following order:
1) If the kwarg `allowed_datastores` is passed, the a datastore is picked from the list with the most free space to capacity ratio and if it 
a) accessible
b) Multiple Host access
c) Overall status is not red
2) If there is a datastore cluster(s), …

[RFR] Add Support For Datastore Clusters for Vmware

---

wrapanapi/systems/scvmm.py

This PR introduces a function for `SCVirtualMachine`, `create_snapshot`, that creates a snapshot (called a checkpoint in SCVMM). This is easily carried out by making use of the `New-SCVMCheckpoint` powershell command. 
Also including a utility function to set the checkpoint type for the VM.

[RFR] Add ability to create a snapshot for SCVirtualMachine

---

wrapanapi/systems/scvmm.py

Adding a utility functions for the following: 
1) Downloading a file 
2) Doing a generic refresh of the SCVMM library
3) Deleting a file
Also, fixing `update_scvmm_library` as it was assuming the name of the VMM Library

[RFR] Add a helper function to download file/VHDs into the library

---

wrapanapi/systems/msazure.py

This affects `test_azure_multiple_subscription` that was not passed in automation for quite some time. Finally, I dug into this and the problem was here.
`list_templates` is essentially `find_templates` that finds all images in all containers.
What we need here is `list_compute_images` as it returns the same result as in `Azure portal -> Images`, that corresponds to `CFME -> Provider -> Images`.

[RFR] fixed count of templates for Azure

---

wrapanapi/systems/scvmm.py

The `refresh_library` function for scvmm hangs, and has been replaced by `Read-SCLibraryShare`, which is already provided by `update_scvmm_library`. This PR is fixing the errors made in #378  
Also adding a function to delete vhd's safely from SCVMM.

[RFR] SCVMM: Removing generic refresh function as it is redundant and broken 

---

wrapanapi/systems/ec2.py

this fixes `cfme/tests/cloud/test_tag_mapping.py::test_labels_update[instances-ec2] FAILED`
example error was as follows
```
<type 'tuple'>: (<class 'botocore.exceptions.ParamValidationError'>, ParamValidationError(u"Parameter validation failed:\nInvalid type for parameter Tags, value: {'tag_label_WWh8gjm227': 'tag_value_AOAuvsaOGY'}, type: <type 'dict'>, valid types: <type 'list'>, <type 'tuple'>",), None)
```
If I pass the dictionary as the first item of the list, the error was:
```
Unknown parameter in Tags[0]: "tag_label_GEkvtZ39Xm", must be one of: Key, Value
```

[RFR] fixed set and unset tag for ec2

---

wrapanapi/entities/vm.py
wrapanapi/systems/ec2.py
wrapanapi/systems/google.py
wrapanapi/systems/msazure.py
wrapanapi/systems/openstack.py
wrapanapi/systems/rhevm.py
wrapanapi/systems/scvmm.py
wrapanapi/systems/virtualcenter.py

abstractmethod and implementations for subclasses of VM
OVIRT and vmware in particular are a real pain in the ass when it comes to addresses
With no reasonable way to determine what's a local network IP and what's a public network IP
Provide a property that just returns all the available addresses, allowing the caller to process them
Changed GCE's properties, as `ip` was returning an internal IP, and `ip_external` should have been `ip`

[1LP][RFR] Add all_ips method to VM entities

---

wrapanapi/systems/scvmm.py

Adding a timezone mapping for windows reported timezones, so that they can be parsed by `pytz`. This allows us to use SCVMM's timezone when getting/setting the `creation_date` of a VM.

[RFR] Add a timezone mapping for windows to pytz and timezone property

---

wrapanapi/systems/openstack.py

Making two changes in this PR:
1) Adding some extra info about args in Docblock.
2) Trying to use regex to check if it contains `v2` or `v3` at the end of auth_url and then set keystone_version based on that. 
3) Added list_keypair() method **-Shinken check around keypair depends on this to be merged.**

[RFR]Updating how auth_url is handled, now parsing keystone_version from it, added List_keypair

---

.travis.yml
requirements.txt

Update for python3 compatibility for travis. 
Version controlling `wait-for` since the latest version has dropped py2 support.
Version controlling `fauxfactory` to v3.0.2 to allow for py2 support.

[RFR] Update travis to use different dist for py2 vs py3

---

wrapanapi/systems/scvmm.py

Was hitting a `TypeError` in this method due to `run_script` returning a bytes string. 
Also updating travis for py3.7 support.

[RFR] py3 compatibility for ip method

---

wrapanapi/systems/scvmm.py

`run_script` returns a bytes string in Python 3, here we try to decode it so that other methods are not broken. 
Also including a fix for `disconnect_dvd_drives` so that the string "+ 1" is parsed correctly. 
```python,
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> int("+1")
1
>>> int("+ 1")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '+ 1'
>>> 
(.cfme_venv) [jdupuy@localhost wrapanapi]$ python2
Python 2.7.16 (default, Apr 30 2019, 15:54:43) 
[GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> int("+ 1")
1
```

[RFR] Try to decode bytes string from run_script

---

wrapanapi/systems/openstack.py

this fixes:
```
>           fip = (ip for ip in self.api.floating_ips.list()
if ip.instance_id is None).next()
E                  AttributeError: 'generator' object has no attribute 'next'
```

[RFR] Use next() instead of calling .next()

---

wrapanapi/systems/scvmm.py

CFME 5.11 images are now zipped for SCVMM, here we're adding a way to unzip them and delete the `ApplicationPackage` (what SCVMM calls the .zip file)

[RFR] Add support for zip files

---

wrapanapi/systems/google.py

Signed-off-by: Nikhil Dhandre <ndhandre@redhat.com>
Not able to reproduce this every time... but as per threads and issue try to turn off it. 
- https://github.com/googleapis/google-api-python-client/issues/299
- https://github.com/googleapis/google-api-python-client/blob/895205850f2825a49138d1240e882a38afe93ffa/googleapiclient/discovery_cache/file_cache.py#L39
fix #408

[RFR] default turn off cache_discovery for gce

---

wrapanapi/systems/openstack.py

Signed-off-by: mnadeem92 <mnadeem@redhat.com>
This method will fetch openstack resource quota values (compute/network/volume) on project basis.
By default, it fetch quota values of all 3 types of the project attached during instantiation of the OpenstackSystem object.
>> get_quota()
However, you can fetch the quotas value to some other project too by passing param project="project-name''
>> get_quota(project='demo')
You can also filter the quota based on its name(compute/network/volume) by passing param name="quota-name"
>> get_quota(name='compute')

[1LP][WIPTEST] Added get_quota method

---

wrapanapi/systems/ec2.py

As we need multiple methods across all the Entities used in EC2 I implementedSharedMethodMixin for these methods same way as it is in other systems.
Tested these methods with every Entity and everything passed.
I had to override rename for CloudFormation stack as this entity is the only one in boto3 that doesn't have rename ability.

[1LP][RFR]SharedMethodMixin for EC2 implemented

---

wrapanapi/systems/msazure.py

Azure iothub wrapper -> add/remove/has_iothub
Required for https://github.com/ManageIQ/integration_tests/pull/9400
Tested locally:
``` python3
from systems.msazure import AzureSystem
azure=AzureSystem(username=username, password=password, tenant_id=tenant,
subscription_id=subid,provisioning=provisioning)
azure.create_iothub("potatoiothub")
Out[3]: <azure.mgmt.iothub.models.iot_hub_description_py3.IotHubDescription at 0x7f838d7b8c90>
azure.has_iothub()
Out[4]: True
azure.delete_iothub("potatoiothub")
azure.has_iothub()
Out[6]: False
```
EDIT:
Also works locally in  https://github.com/ManageIQ/integration_tests/pull/9400 with this PR.

[1LP][RFR] Azure iot client, create/add iothub

---

wrapanapi/systems/rhevm.py

When running VM Console tests, Pressing Ctrl+Alt+del causes 'reboot_in_progress' api_state, we need have a map to handle it. 
I was seeing 
```Unmapped VM state 'reboot_in_progress' received from system, mapped to 'VmState.UNKNOWN' ```
and hence this fix. It is apt to map it to state `VmState.STARTING` as that is what ultimately happens when you are Rebooting.

[RFR]Adding ability to handle state reboot_in_progress

---

wrapanapi/systems/container/rhopenshift.py

I thought it had been fixed. unfortunately, it's still present. this PR should get rid of this issue.
```
2019-12-02 08:43:20,805 [W] [py.warnings] ./.cfme_venv/lib64/python3.7/site-packages/wrapanapi/systems/container/rhopenshift.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
```

[1LP][RFR] fixing collections warning

---

wrapanapi/systems/rhevm.py

Allow setting the root_password and authorized ssh key in rhev
This addition enables setting of the root password and authorized ssh
key when deploying new vm from template on rhev

[RFR] Allow setting the root_password and authorized ssh key in rhev

---

wrapanapi/systems/base.py

There was a typo introduced 4 months ago and def stats in systems/base.py is broken.

Typo fix so validate_stats for providers not working

---

wrapanapi/systems/ec2.py

CFME doesn't count terminated(archived) instances in instance count so we need to do same in wrapanapi.

[RFR]Deleted instances should be hidden so we can compare with cfme

---

wrapanapi/systems/ec2.py

Currently routers/subnets with tags that don't have Name tag are not listed at all.
With this PR id should be listed.

[RFR]List routers/subnets that have tags and don't have Name tag

---

setup.cfg

``` 
RuntimeError:
Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
Please install the service specific packages prefixed by `azure` needed for your application.
```

Set azure meta package version to <5.0.0

---

wrapanapi/systems/ec2.py

We use some public images for our tests and get_template was checking only owned/private images.

[RFR]get_template should also check public images

---

setup.cfg

botocore requires update 
update reasoning is explained in [this](https://github.com/SatelliteQE/robottelo/issues/8332) robottelo issue.
My steps:
I found  boto and boto3 is dependant, boto version is not specified in `setup.cfg` but boto3 is so I looked at boto3 versions and found 1.12.0, random release that was after 1.14.0. 
Then I let pip to installed boto3
`pip install boto3 == 1.12.0` and ` botocore >= 1.14.0 ` and pip installed `botocore 1.15.49`

update botocore version

---

wrapanapi/systems/msazure.py

Closes #444 .
Additionaly, this PR adds a single function to remove all unused resources called `cleanup_resources()`.

Remove all unused Disks, PIPs and NICs from a resource group

---

wrapanapi/systems/openstack.py

**Fixes:**
```
In [1]: from wrapanapi.systems.openstack import OpenstackSystem
ModuleNotFoundError: No module named 'cinderclient.v2'
```
**Details:**
Removal of `cinderclient.v2` - https://opendev.org/openstack/python-cinderclient/commit/6ebee33bf219d42fcd0d4bf2a8c0819bddb24f3c

Use cinderclient.v3 as cinderclient.v2 is removed

---

setup.cfg

We have no direct requirements, and its not installed as a dependency of
any of our existing requirements.
setuptools 58 broke install of suds-jurko because of use_2to3, and the
project is abandoned

Remove suds-jurko requirement

---

setup.cfg

```
>>> from wrapanapi import EC2System
>>> client = wrapanapi.EC2System(username='username', password='password', region='us-west-2')
>>> client.create_vm('ami-0686851c4e7b1a8e1')
<wrapanapi.systems.ec2.EC2Instance system=<EC2System> raw=<boto3.resources.factory.ec2.Instance>, kwargs['uuid']='i-uuid'>
>>> client.list_vms()
[<wrapanapi.systems.ec2.EC2Instance system=<EC2System> raw=<boto3.resources.factory.ec2.Instance>, kwargs['uuid']='i-uuid'>]
```

unpin the boto from setup.cfg

---

wrapanapi/systems/msazure.py

added option to delete whole group if all resources are older than `hours_old`. deleting individual resources would be difficult due to inability to delete dependent resources.

 delete whole azure group

---

.github/workflows/release_to_pypi.yml

action failed not finding v1.4.2, even though its available in marketplace. Moving to more generic v1 specifier

More generic release version for gha-pypi-publish

---

pyproject.toml

Updating the pyvcloud that uses `yaml.safe_load()` to fix the CVE-2017-18342

Update pyvcloud to fix CVE CVE-2017-18342

---

wrapanapi/systems/google.py

* wrapanapi queries the whole project for templates instead of asking the GCE API for a subset of templates.
* expose the filter expression argument that is passed to the GCE API that filters the templates based on the expression provided
GCE documentation: https://googleapis.github.io/google-api-python-client/docs/dyn/compute_v1.images.html#list

Make GoogleCloudSystem.find_templates more memory-efficient by using a filter

---

wrapanapi/systems/ec2.py

This is needed to obtain bucket's creation time as follows
s3_client.get_bucket_tagging(Bucket=bucket.name)
In the future, it might be replaced by resourcegroupstaggingapi

Add s3 client

---

.github/workflows/pull_request.yml

In #471, we have hit issues running wrapanapi unit tests with Python 3.8. Errors related to `typing` library were showing up.
Unit tests using Python 3.9 do not throw any error, therefore we can drop Python 3.8. 
After talking to @mshriver, we should be good to drop Python 3.8 since all known wrapanapi users are using 3.9+.

Drop Python 3.8 support

---

pyproject.toml

Since we deprecated Python 3.8 in #473, we should set the minimal Python version that wrapanapi requires in its project settings.
Add `requires-python` option to pyproject.toml and set it to 3.9+.

Add requires-python option to the project config

---

pyproject.toml
wrapanapi/const.py
wrapanapi/systems/ec2.py

Main changes:
- Updated some features to the EC2Instance class:
- Set id property and repr func
- Updated some features to the ResourceExplorerResource class:
- Set modified date ("LastReportedAt") and 
- Set an EC2 Instance object for a matching type resource
- Updated `list_resources` flow to catch and log client error when using ResourceExplorer through an unauthorized client

 Add support for collecting deletable OCPs from AWS

---

wrapanapi/systems/google.py

The `is_zone_operation_done` of class `system` does not `_zone` attribute set and hence the delete operation has been failing for missing `zone` even though the operation was performed successfully in the background.

GCE stop and remove operations needs explicit zone

---

pyproject.toml
wrapanapi/__init__.py
wrapanapi/systems/container/__init__.py
wrapanapi/systems/container/podman.py

PR adds:
- The new podman system in the support for container type resource
- New podman requirement is added
- The podman system belongs to container systems package 
- The class `PodmanContainer` represents the podman container and has properties and functions around it.
Blocks:
- https://github.com/RedHatQE/cloudwash/pull/140

Podman Containers client support

---

pyproject.toml

Pinned the pyOpenSSL package as the deprecated sign function in 24.3.0 is causing the failures. Hence pinning the version for now.

Pinning the pyOpenSSL as deprecated sign function causing failures

---

pyproject.toml

Problem Statement:
Robottelo uses uv to install all the dependencies in robottelo and somehow it is installing azure 2.0.0 as it is not able to resolve the dependencies correctly. 
However, when we use pip to install the dependencies, it correctly installs azure 4.0.0. 
Solution:
To avoid the issue, we are pinning azure version to 4.0.0.

Pin azure version to install correct version

---

pyproject.toml

PyOpenssl version of 22 is being installed when uv package manager is being used for installation when set with less than operator.
Hence pinning to specific version.

WrapanAPI pinned again

---

wrapanapi/systems/virtualcenter.py

```
In [1]: from wrapanapi import VMWareSystem
...: from wrapanapi.systems.virtualcenter import VMWareVirtualMachine
In [2]: vmwareclient = VMWareSystem(
...:         hostname=vmware.hostname,
...:         username=vmware.username,
...:         password=vmware.password,
...:     )
In [3]: vm = vmwareclient.get_vm('heidi-detten.example.com')
In [4]: vm.get_virtual_device_type_names()
Out[4]:
['VirtualController',
'VirtualKeyboard',
'VirtualPointingDevice',
'VirtualVideoCard',
'VirtualVMCIDevice',
'VirtualDisk',
'VirtualEthernetCard',
'VirtualTPM']
```

Add method to fetch virtual devices attached to VM on VMware

---

wrapanapi/systems/msazure.py

PS:
----
- The Azure listing VMs function is not using resource group attr set in the client object, where other list functions do
Resolution:
-----------
- Using client resource group now to list VMs

Azure VMs listing honours the client resource group now
