mgmtsystem/__init__.py
mgmtsystem/azure.py

This is a sample script which has been tested to verify the implemented methods.  It shows an example of initiating the class and passing parameters to the methods.
http://pastebin.test.redhat.com/338998
The password will be stored in credentials.

Initial Azure RM Management System

---

mgmtsystem/openstack.py

This enables you to control the floating IPs from outside comfortably.

[Openstack] Extracted FIP logic into separate methods.

---

mgmtsystem/openstack_infra.py

Signed-off-by: Pete Savage <psavage@redhat.com>

Added OpenStackInfra

---

mgmtsystem/scvmm.py

* removed the parameters, which are not in use.

Fix scvmm template deploy.

---

mgmtsystem/scvmm.py

The scvmm powershell method had issues with RHEL images that the Hyper-V method does not.  Most google posts said this is the most reliable way to install guest services and Amogh and I tested it on a variety of OS types and didn't fail.  SCVMM 2016 fixes this issue but doesn't help us now.

Change enable_virtual_services to install via Hyper-V instead of SCVMM

---

README.rst
mgmtsystem/__init__.py
mgmtsystem/hawkular.py
mgmtsystem/rest_client.py

Added new class for Hawkular REST API methods. Created new method in rest_client to return JSON only.

Hawkular integration: Initial commit.

---

mgmtsystem/scvmm.py

* add -Force flag to delete the vm
* remove the host parameter, which is not really used.

Fix delete_vm for scvmm.

---

mgmtsystem/hawkular.py
tests/test_hawkular.py

Added '_stats_available' for crud tests in cfme_tests.

Modified Hawkular to extend from MgmtSystemAPIBase

---

mgmtsystem/scvmm.py

Changes made with Amogh.  Tested using.  
def test_get_ip_address():
vm_name = 'test_scvmm_vm'
sc = SCVMMSystem(**scvmm_args)
sc.start_vm(vm_name)
vm_getip = sc.get_ip_address(vm_name)
assert vm_getip == "1.2.3.4"

[FIX] Updated get_ip to force a SCVMM refresh on VM first

---

mgmtsystem/hawkular.py
tests/test_hawkular.py

Is there an alternative of "sys.maxsize" to get Long.MAX_VALUE?

Added new method to list events of Hawkular, added tests.

---

mgmtsystem/hawkular.py
tests/test_hawkular.py

[WIP] Added new REST API method to list datasources on Hawkular side. 

---

mgmtsystem/virtualcenter.py

* get_vm_host and get_vm_datastore_path methods
are added. These attributes can be used to check
vm files.

Add methods to fetch vm host and vm datastore path.

---

mgmtsystem/virtualcenter.py

* add method to get_vm_config_files_path and compare
datastore path with vm config file path.

add method to vm_config_files_path.

---

mgmtsystem/openstack.py
mgmtsystem/rhevm.py
mgmtsystem/virtualcenter.py

Able to override some HW parameters during provisioning. RHEV and vSphere can override CPU and RAM and RHOS learned to use ids to retrieve flavours.

Hardware configuration (CPU, RAM) during deployment

---

mgmtsystem/azure.py

Simple fix to swap out the hardcoded data store value.  Cleaned up the script while I was looking at it.
Ran locally against provider crud and worked fine.

[FIX] Replaced hardcoded Storage Account, cleaned up Script

---

mgmtsystem/azure.py

All of this is needed for Power Control.  I have to use a default resources_group otherwise every method will generate and exception.  Azure cannot find a vm based solely on it's name, it has to have a resource group.  CFME_TEST instance methods do not pass this value.

Azure deploy_template rollout, plus delete_vm

---

mgmtsystem/azure.py

Cleaned up a bunch of the start, stop, suspend methods and added wait method calls to each.  Cleaned up the wait methods.  Cleaned up is methods to return true instead of vm name.  Most power control tests are now passing.

Cleaned up all the wait methods, added suspend, fixed some errors.

---

mgmtsystem/azure.py

Single line addition to also remove the Public IP.  Apparent others couldn't do any testing as we were out of IPs for that subnet range.
Tested locally and works fine.

Enhanced delete_vm to also remove Public IP resource.

---

mgmtsystem/virtualcenter.py

* list_host_datastore_url method is added to virtualcenter.

Add list_host_datastore_url method to virtualcenter api.

---

mgmtsystem/azure.py

Didn't realize the subnets had to be unique across regions.  Tested locally.  Need for azure power control.

[FIX] Replaced hardcoded subnet with yaml to allow for multiple regions

---

mgmtsystem/hawkular.py
tests/resources/hawkular/inventory/feeds/328c17e1-c97f-4583-89d8-73feb0cf47f6/resourceTypes/Domain WildFly Server/resources.json
tests/resources/hawkular/inventory/feeds/328c17e1-c97f-4583-89d8-73feb0cf47f6/resourceTypes/Host Controller/resources.json
tests/resources/hawkular/inventory/feeds/5ea2d44a-6b07-424b-b54e-0b4c798d1353/resourceTypes/Domain WildFly Server/resources.json
tests/resources/hawkular/inventory/feeds/5ea2d44a-6b07-424b-b54e-0b4c798d1353/resourceTypes/Host Controller/resources.json
tests/resources/hawkular/inventory/feeds/c22fb9d6-0ffc-42cd-bf5b-e1d046398fe5/resourceTypes/Domain WildFly Server/resources.json
tests/resources/hawkular/inventory/feeds/c22fb9d6-0ffc-42cd-bf5b-e1d046398fe5/resourceTypes/Host Controller/resources.json
tests/resources/hawkular/inventory/feeds/master.eap7%20domain/resourceTypes/Domain Server Group/resources.json
tests/resources/hawkular/inventory/feeds/master.eap7%20domain/resources/Host Controller/data.json
tests/resources/hawkular/inventory/feeds/master.eap7%20domain/resources/Local~~/Local~%2Fserver-group%3Dmain-server-group/data.json
tests/test_hawkular.py

Added new function to prepare resource_id if it is array.
Added testcases and mock json objects for it.

Added new functionality to retrieve Server Group and Domain from Hawkular-Inventory

---

mgmtsystem/google.py

I couldn't find anything calling create_vm but someone should double
check.
deploy_template is what test_vm_disco, test_power_ctl, and everthing?
else uses

move create_vm to deploy_template

---

mgmtsystem/azure.py

There's a lot here.  Perhaps a meeting to review would be best.

Overhaul Cleanup methods, implement vm_creation_time, other.

---

mgmtsystem/google.py

Without create_vm method abstract class GoogleCloudSystem can't be instantiate

Fix for GCE

---

mgmtsystem/azure.py

Added list_stack, stack_exist, and delete_stack to support Orchestration automation efforts for Shveta.  Cleaned up a few other returns while I was in there.
Thoroughly tested with these unit tests - http://pastebin.test.redhat.com/411048

Azure - Added Stack Methods for list, exists, and delete

---

mgmtsystem/hawkular.py

https://github.com/ManageIQ/wrapanapi/pull/64 introduced this issue.

Fix: make _stats_available on Hawkular object

---

mgmtsystem/hawkular.py

Extended hawkular alerts api support.
* `list_alert`
* `list_trigger`
* `get_single_trigger`
* `create_trigger`
* `delete_trigger`

Extend hawkular alert api

---

mgmtsystem/ec2.py

* create_s3_bucket() and upload_file_to_s3_bucket() methods are
added to EC2.py
* template_uploade_ec2 script invokes these methods to upload ec2 images.

add amazon s3 methods to create_bucket and upload_file.

---

mgmtsystem/azure.py

At the moment we are working with Azure provider via Azure PowerShell cmdlets by pushing our scripts into WinMR(wsman) service on Windows machine( scvmm2 right now)
I have described some recent error messages that we are getting during test setup in __https://projects.engineering.redhat.com/browse/RHCFQE-1095__
All of them are mainly due to some connection/transmission issues
So it'd be better to rerun script few times (main one that fails is vm_status)

Azure run_script checks&retries

---

mgmtsystem/base.py
mgmtsystem/rhevm.py
mgmtsystem/virtualcenter.py

get_vm_guid(): Slow universal implementation + fast one for vSphere and RHEV-M

---

mgmtsystem/hawkular.py

Support added to query metric data for JMS queue/topic `list_jms`

[Hawkular] Adding support for JMS queue/topic metric query

---

mgmtsystem/azure.py

Some my tests need to remove blob images in order to clean up environment. 
So, I updated azure's remove_blob_image method to accept different containers instead of certain one defined in cfme_data.yaml

removed certain folder restiction from remove_blob_image

---

mgmtsystem/google.py

* vm_creation_time method is added to gce api lib. the vm_creation time stamp is in iso8601 for gce instance, that is been parsed using iso8601 python lib.

Added vm_creation_time method to google.

---

mgmtsystem/kubernetes.py
mgmtsystem/openshift.py

Removed images from STATS_TO_MATCH for the time being

Modified API to account for the new image feature in CFME 5.7

---

mgmtsystem/exceptions.py
mgmtsystem/google.py

add some methods to receive information about forwarding rules.

Load balancers

---

mgmtsystem/google.py

* vm_type method is added to gce api lib.

Added vm_type method to google. (#89)

---

mgmtsystem/openshift.py

Added template object to mgmtsystem/openshift.py

[RFR]Added template functionality to mgmtsystem/openshift.py

---

mgmtsystem/rest_client.py
mgmtsystem/utils/__init__.py
requirements.txt

Added strings evaluation functionality to rest_client.ContainerClient.get to allow types parsing.
Description in function code.
Added requirement: [dateparser](https://pypi.python.org/pypi/dateparser)

Added strings evaluation functionality to rest_client.ContainerClient.get

---

mgmtsystem/scvmm.py

"-Force" was only removing VM from VMM interface but it stays in cluster and datastore. To bring such VMs back to VMM's UI - update_scvmm_vmhost.

[RFR]changes in scvmm.py to fix cleanup

---

mgmtsystem/kubernetes.py

Added 2 new functions: list_replication_controller_labels() and num_replication_controller_labels()

[RFR]Added functionality for the rc labels

---

mgmtsystem/scvmm.py

Reverts ManageIQ/wrapanapi#100

Revert "[RFR]changes in scvmm.py to fix cleanup"

---

mgmtsystem/scvmm.py

removing hardcoded hostname and adding method to get VM's Host

[RFR]fix for cleanup on scvmm without hardcoded host

---

mgmtsystem/ec2.py

Added connections - added region to them, added unused elbs listing, deleting elb, deleting sqs queue.
Also added region to cloudformation connection.

Added connections/methods for sqs and elb

---

mgmtsystem/openshift.py

Added function to collect images from Openshift, excluding those created by running pods

[RFR]Added function list_image_openshift

---

mgmtsystem/scvmm.py

This extends deploy_template to use custom ram and cpu values if requested, but only if they are equal to or greater than the existing values as scvmm prohibits deploying templates that are smaller than the template definition.  The minimum default values are included in the yaml.
This is required to fulfill mfalesni's request for this additional functionality.

[RFR] Extend deploy_template to use cpu and ram if specified.

---

mgmtsystem/openstack.py

Sample log output:
```
2017-02-03 17:44:52,287 [I] RAM/CPU override of flavour CFME: RAM 16834, CPU: None (/home/mfalesni/git/mgmtsystem/mgmtsystem/openstack.py:467)
2017-02-03 17:44:52,549 [I] Found a flavour CFME-16834M-6C (/home/mfalesni/git/mgmtsystem/mgmtsystem/openstack.py:507)
2017-02-03 17:44:59,381 [I] RAM/CPU override of flavour CFME: RAM 12000, CPU: None (/home/mfalesni/git/mgmtsystem/mgmtsystem/openstack.py:467)
2017-02-03 17:44:59,656 [I] No suitable flavour found, creating a new one. (/home/mfalesni/git/mgmtsystem/mgmtsystem/openstack.py:482)
2017-02-03 17:44:59,913 [I] Created a flavour u'CFME-12000M-6C' with id u'8435a030-f313-48e1-b31c-f2907ba48fb9' (/home/mfalesni/git/mgmtsystem/mgmtsystem/openstack.py:504)
2017-02-03 17:45:08,178 [I] RAM/CPU override of flavour CFME: …
```

Openstack: Override RAM/CPU, auto create flavour

---

mgmtsystem/azure.py

Aligned the yamls to the data to the management system.  There was way too much guessing going on between systems.  Now everything is explicit.

[RFR]Leave .vhd in template name.  Remove adding .vhd when creating vm.

---

mgmtsystem/azure.py

This has been in my JIRA inbox for a while.  Add two methods for listing and verifying that a load balancer exists.  Unit tested local for both pass and fail and it worked correctly.

[RFR]Added Azure Load Balancer methods for List and Does exist

---

mgmtsystem/scvmm.py

Enhances deploy_template.  Tests are failing when an invalid template name is passed into the method.  Simple solution is to check for the template name before attempting to deploy it and log an easy to read warning on why the we didn't create the VM.  It's only a three line change despite what gh thinks.  It's pretty straight forward.

[RFR]Deploy Template raising exception when invalid template name is passed

---

mgmtsystem/azure.py

adding functions as part azure_cleanup task

[RFR]adding azure cleanup functions

---

mgmtsystem/azure.py

this Pr includes fix of currently broken vm_status and get_vm_vhd

fix for broken azure's vm_status method

---

mgmtsystem/scvmm.py

…as explicitly asserted.
This was a corner case @mshriver  found during template upload review.  Promised him I would fix it.
Unit tested both changes for true and false values.

Fixed corner case where exception possible.

---

mgmtsystem/ec2.py
requirements.txt

Boto3 added to requirements
S3 connection is now refactored with boto3
S3 create_bucket now works with region

Added boto3 to requirements and refactored amazon s3 for boto3

---

mgmtsystem/ec2.py

This all works with boto3 ec2 connection.
Tested on many AWS regions.
Maybe image_import should return tuple? ImageID and TaskID?

Added import image, get import image task status, is_image_import_completed and copy image

---

mgmtsystem/hawkular.py
requirements.txt
tests/resources/hawkular/inventory/feeds/5ea2d44a-6b07-424b-b54e-0b4c798d1353/resources/Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DExampleXADSMWTest/data.json
tests/resources/hawkular/metrics/status.json
tests/test_hawkular.py

Added check based on metrics version to choose HawkularInventory or HawkularInventoryInMetrics class.

[RFR] Added new HawkularInventoryInMetrics client class for Hawkular Inventory REST API in Hawkular Metrics.

---

mgmtsystem/azure.py

This allows user to override the "automation" resource_group per discussion with @mshriver 
Unit tested locally.

[RFR]Added resource group param to list_vm

---

mgmtsystem/ec2.py

Maybe I should change parameter object_key to array of keys rather than for single key?

Added check for existing objects in bucket

---

.gitignore
requirements-test.txt
requirements.txt
tests/test_virtualcenter.py
wrapanapi/virtualcenter.py

Migrate VMWareSystem from psphere to pyVmomi, with help from @anewmanRH.
psphere added a number of utility methods to the vSphere API objects, so I had to write some methods to achieve the same thing. Please feel free to critique.
Added a couple of tests, most specifically around the custom methods I wrote.

[1LP][RFR] Pyvmomi migration

---

wrapanapi/virtualcenter.py

Fix a couple small issues with either None being logged, or an unexpected object being present.

[RFR] Fix some logging issues

---

wrapanapi/ec2.py

Methods to manage S3 bucket objects and AMI's

[RFR] Update ec2, add delete_objects_from_s3_bucket() and deregister_image()

---

wrapanapi/ec2.py

dammit.
At least it doesn't break import.

Fix ec2 typo

---

wrapanapi/virtualcenter.py

So manageiq/integration_tests/scripts/template_upload_vsphere was directly using the `VMWareSystem.api` property that existed before the conversion to pyVmomi.  That migration broke this use.
Adding a disk to VM was one of the most api 'heavy' tasks in that script, moving the functionality into wrapanapi directly.
Used the pyVmomi community guide example as a reference:
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_disk_to_vm.py
Currently testing locally.
FIXES RHCFQE-3288

[RFR] Add virtualcenter.add_disk_to_vm

---

wrapanapi/azure.py
wrapanapi/scvmm.py

The creation time doesn't have a TZ, have to localize first before calling `astimezone()`
Same needs to be applied to Azure.

Fix scvmm and azure vm_creation_time()

---

wrapanapi/ec2.py

Tested with automated tests done by me

Added SNS topic methods & bucket delete

---

wrapanapi/ec2.py

Options to modify are now:
image_id,
min and max count,
instance_type,
name
Going to add some more some other day
Also have TODO to check if instances were really created.

EC2 instance create method - only for basic usage now

---

wrapanapi/azure.py

due to unknown issue on Azure we are getting incorrect last_modified date, which update with the script run:
vm test-prov-bl5o - 2017-07-24 11:39:39
vm test-prov-mt7c - 2017-07-24 11:39:57
vm test-prov-nmzp - 2017-07-24 11:40:19
vm test-prov-npsw - 2017-07-24 11:40:37
vm test-prov-qxny - 2017-07-24 11:40:54
and our cleanup jobs are failing - some VMs stay on provider side for 15+hours until they stop updating  LastModified of their OSDisk (couldn't find any clues on that)
So the idea is to get last activity log of our VM and get it's timestamp. 
__outdated:__ Unfortunately looking for logs older than 15h is a problem - too long and it fails to fetch results. For sake of housekeeping activities we could take only 12h old logs.

[RFR]changing azure vm last modified source

---

wrapanapi/containers/__init__.py
wrapanapi/containers/deployment_config.py
wrapanapi/containers/image_registry.py
wrapanapi/containers/project.py
wrapanapi/containers/providers/openshift.py
wrapanapi/exceptions.py

**This PR depends on https://github.com/ManageIQ/wrapanapi/pull/161** 
- Added name validation for several resources.
- Added deployment config creation
- Added image import functionality for image registry

[RFR] Added image import and deployment config creation

---

wrapanapi/azure.py

fixed few network methods as they were not working. found that while was testing latest Azure Module 4.2

[RFR]fixing few methods

---

wrapanapi/azure.py

this will be part of housekeeping activities on azure provider

[1LP][RFR]script to remove unused blobs

---

wrapanapi/ec2.py

Copy snapshot is not working due to boto3 bug, which is going to be reported.
The rest is needed for automation tests.

Added volume & snapshot check + copy snapshot

---

wrapanapi/containers/__init__.py
wrapanapi/exceptions.py

- Fix delete labels - the function remove all the labels.

[RFR] Fix delete label + LabelNotFoundException

---

wrapanapi/rhevm.py

Change-Id: Iac00f86aa9aca06f9ad0cb807c1dc79d4d6b9c5d

Fix for including filter true on API headers

---

wrapanapi/rest_client.py

- Added logger for rest client

[RFR] Logging rest_client

---

wrapanapi/msazure.py

adding vm_type - needed in list_provider_vms.py or just in case

[RFR]adding vm_type

---

wrapanapi/scvmm.py

1. removed "-Force" - currently VMs are removed from inventory only - we run out of space without manual cleanup
2. list_vm_providers.py uses vm_hardwareconfiguration method - added

[1LP][RFR]small fixes for SCVMMSystem

---

wrapanapi/exceptions.py
wrapanapi/openstack.py

Adding Keystone V3 client for OSP management system since v2 is deprecated and doesn't work properly on latest RHOS releases

[RFR] add keystone v3 for Openstack cloud

---

wrapanapi/scvmm.py

covers RHCFQE-5127 and https://gitlab.cee.redhat.com/cfme-qe/cfme-qe-yamls/merge_requests/327
updating particular path\folder runs 10 times faster

[RFR]updating library accordingly to yamls

---

wrapanapi/base.py
wrapanapi/containers/providers/kubernetes.py
wrapanapi/ec2.py
wrapanapi/google.py
wrapanapi/hawkular.py
wrapanapi/msazure.py
wrapanapi/openstack.py
wrapanapi/openstack_infra.py
wrapanapi/rhevm.py
wrapanapi/scvmm.py
wrapanapi/virtualcenter.py

This makes it so that containers doesn't need to follow the other patterns and gives a base for Lenovo

Moved to Base

---

wrapanapi/scvmm.py

[RFR] Added list_cluster for SCVMM

---

wrapanapi/__init__.py
wrapanapi/lenovo.py

This PR is able to:
- Add actions methods to LenovoSystem
Depends on #186 and #190
- I'll make a rebase after the dependencies are merge

Wrapanapi actions methods

---

wrapanapi/lenovo.py
wrapanapi/nuage.py

* Added Nuage skeleton
* Fixed Lenovo bug

Added Nuage skeleton

---

wrapanapi/virtualcenter.py

Fix a bug where a type should have been a Python class but was a string instead

Fix a TypeError bug

---

wrapanapi/__init__.py
wrapanapi/nuage.py
wrapanapi/utils/json_utils.py

Hi @psav,
this is the initial version of the Nuage client for wrapanapi. It's still a work in progress, but i would like some input, if we are heading in the right direction. If not, any information on how to continue would be welcome. 
/cc @gberginc

[RFR] Add nuage client implementation with some of the basic methods

---

wrapanapi/lenovo.py

This PR adds the physical server power state stat and implements the _stats_ method.

Add power state stat and stats method

---

wrapanapi/rest_client.py

In case that the request failed the returned json content is None, that make it almost impossible to debug. In this PR we are changing that to always return the json content.

[RFR] Return json content even if request failed (r.ok != True)

---

wrapanapi/msazure.py

Extending cleanup with resource_group handling and subscription managment

[RFR] Azure cleanup

---

wrapanapi/lenovo.py

This PR is able to:
- Add a new hash `_inventory_available` for match with the data view in the Integration Tests.
Depends on : [PR  197](https://github.com/ManageIQ/wrapanapi/pull/197)

[RFR]  Add a new hash attribute for retrieve inventory information  - Lenovo Provider

---

wrapanapi/containers/image.py
wrapanapi/containers/providers/kubernetes.py
wrapanapi/containers/providers/openshift.py

1. Added an option to get Pod/Service for a specific project.
2. Added image_project_name for an image. At the moment the image object returns None for project_name parameter and I can't seem to overwrite it or access it. I ran out of ideas, this works

[1LP][RFR] Added Pods/Services for a specific project

---

wrapanapi/base.py
wrapanapi/nuage.py

With this commit we update  NuageSystem to actually become usable for our first CRUD integration test. Current implementation was not fully functional yet, therefore we changed quite a lot.
As of now, we only support three entities: cloud_subnets, security_groups and network_groups, because Nuage provider currently only inventories these three.
Here is the PR that actually uses the NuageSystem: https://github.com/ManageIQ/integration_tests/pull/6499
@psav I kindly ask for a review.

[RFR] First time actually use Nuage skel

---

wrapanapi/msazure.py

https://docs.microsoft.com/en-us/python/api/azure.mgmt.compute.v2017_03_30.models.disk?view=azure-python

Change disk.owner_id to disk.managed_by as per latest azure sdk

---

wrapanapi/lenovo.py

Allows a different port to be used for API

[RFR] Fixed port accessibility for Lenovo

---

wrapanapi/msazure.py

cleanup_azure was hitting exceptions when removing unused blobs that had snapshots present
So `remove_unused_blobs` will now handle blobs where snapshots are present, I've chosen to catch the exception and log a warning so we know what happened under the hood instead of just specifying `delete_snapshots="include"` at the initial delete call.

[RFR] Remove snapshots from unused blobs

---

wrapanapi/containers/providers/rhkubernetes.py

Added an option to get Containers for a specific project.

[1LP][RFR] Update rhkubernetes list_container support a specific project filter

---

wrapanapi/google.py

Hot fix.
Previously raised an exception.

[RFR] Fixed delete_bucket on GoogleCloudSystem

---

wrapanapi/ec2.py

__Adding__ `list_stacks()` which returns EC2 boto Stack Object
i.e. this will be used in stack removal cleanup job

[RFR]adding list_stacks

---

wrapanapi/google.py

Added function to work with templates and files in bucket:
- __delete_file_from_bucket__ useful for cleaning up
- __delete_image__ useful for cleaning up
__Minor:__ fixed log messages

[1LP][RFR] Added delete_file_from_bucket & delete_image to GoogleCloudSystem

---

wrapanapi/msazure.py

updating get_ip_address: public_ip object might be named not like instance or network_interface.
But to make it work we have to go though  getting all objects and their ids on our way to the public_ip_obj

[1LP][RFR]fix for get_ip_address

---

wrapanapi/containers/providers/rhopenshift.py

Sometimes pod appliances are removed from sprout but not removed from openshift provider. This PR should fix such issues.

[1LP][RFR] fix of issue when pod appliances are sometimes not removed

---

wrapanapi/msazure.py

Get a list of available geo-locations
NOTE: This operation provides all the locations that are available for resource providers;
however, each resource provider may support a subset of this list.
Return: list of tuples - (name, display_name)

[1LP][RFR]added list_region

---

wrapanapi/rhevm.py

Newly created VMs are sometimes assigned IPv6 address before IPv4. If we then want to SSH to such VM, we've got a problem. This PR ensures that we can force waiting for IPv4. Example of where this might be relevant is [here](https://github.com/ManageIQ/integration_tests/blob/5f886b73af84ff5b97a41d335eb293972d66544d/cfme/tests/infrastructure/test_cloud_init_provisioning.py#L68).

[RFR] Option to verify IPv4 when getting VM's IP address from RHV

---

requirements.txt
wrapanapi/exceptions.py
wrapanapi/rhevm.py

@quarckster moved this along quite nicely, hes more fluent on the state of it than i now

[1LP][RFR] ovirtsdk v4 update

---

wrapanapi/lenovo.py

This PR adds methods to the LenovoSystem class that retrieve details about network and storage devices.
Depends on PR https://github.com/ManageIQ/wrapanapi/pull/250

[1LP][RFR] Add network and storage device support to LenovoSystem

---

wrapanapi/containers/providers/rhopenshift.py

This is just temporary fix. I think how to implement this in better way.

[RFR] changed default version to 5.9

---

wrapanapi/rhevm.py

This PR is needed by https://github.com/ManageIQ/integration_tests/pull/6985

[RFR] Added new methods to RHEVMSystem

---

wrapanapi/msazure.py

Fix to avoid cleanup job failure in case we pick up fresh Network interface which was just created hence doesn't have any VM.

[1LP][RFR]fix to avoid new nic removal

---

wrapanapi/containers/providers/rhopenshift.py

There is some stuff in openshift module, which needs to know appliance version.
Sprout creates appliances with name which don't give enough information about version of deployed appliance.
This PR makes deploy_template store appliance version in project description and make it available for the rest of stuff.
In addition, it adds regexps which will be able to parse some of sprout project names and extract at least some information about version like stream.

[1LP][RFR] better appliance version handling in openshift

---

requirements.txt
setup.cfg
tox.ini
wrapanapi/google.py

this one needs a priority review
whops, black did it worse than expected, i#ll redo the parts

[RFR] Fix build - fixes google api and sorts out latent issues

---

wrapanapi/rhevm.py

attribute error from reference to storagedomainservice.storage_connections
pulling storage_connections_service and calling list

Fix rhevm.get_storage_domain_connections

---

wrapanapi/rhevm.py

More ovirtsdk fixes, including a new method to update template nics in the same way that vm nics are updated. 
Added vnic_profile setting to vm_nic and template_nic update - only setting the network was not sufficient.

[1LP] Update RHEVMSystem ovirtsdk4 use

---

wrapanapi/containers/providers/rhopenshift.py

This Pr fixes issue when one of openshift provider instances gets incorrect auth hash during connection. It happens only when there are several different openshift providers are used. 
I also tried to update openshift client to version 5.0 but it turned out that it had some issues. so, I had to roll back client upgrade. Furthermore, there is new dynamic openshift client which replaces current generated client. So, it doesn't make sense to migrate to intermediate version.

[RFR] make wrapanapi->openshift use latest openshift client

---

wrapanapi/systems/ec2.py

[RFR] Fix ec2 template searches

---

wrapanapi/systems/msazure.py

Hit during wrapanapi 3.x testing

Tweaks for a couple azure issues

---

wrapanapi/systems/scvmm.py

Fixing errors seen in wrapanapi 3.x testing

Add retry logic when a 1600 error is hit in scvmm deploy

---

wrapanapi/systems/lenovo.py

this PR refactors the Lenovo System, so that it can be more concise when we add more physical components to its structure.

[1LP][RFR] refactor lenovo system

---

wrapanapi/systems/ec2.py
wrapanapi/systems/google.py
wrapanapi/systems/msazure.py
wrapanapi/systems/openstack.py
wrapanapi/systems/rhevm.py
wrapanapi/systems/scvmm.py

instance_view is empty if refresh hasn't occurred.

Refresh azure instance before property fetch

---

requirements.txt
wrapanapi/systems/ec2.py
wrapanapi/systems/openstack.py
wrapanapi/systems/rhevm.py
wrapanapi/systems/scvmm.py
wrapanapi/systems/virtualcenter.py

Fix _get_images_service to use StorageDomainService
Update kwargs for import_glance_image so it isn't confusing
WIPTEST because of updates to mark_as_template, everything else tested.

[1LP][RFR] Update rhevm, openstack nic and template functions

---

wrapanapi/systems/openstack.py

FloatingIpPool is required when we create IP. other way we `return None`

[1LP][RFR]fix for creating floating ip method

---

wrapanapi/systems/nuage.py

We were missing _identifying_attrs function hence everything exploded. It works now.

[RFR] Port Nuage System to wrapanapi v3 format

---

wrapanapi/systems/openstack_infra.py

@Jad Is having an issue with openstack infra authentication, opening this up for him to try as a workaround in his environment, converting the API objects in `OpenstackInfraSystem` to use a common keystone session object.
Ripped straight from `OpenstackSystem`.

[RFR] openstack infra auth via keystone session

---

wrapanapi/systems/scvmm.py

An issue for SCVMM
local test:
http://pastebin.test.redhat.com/641319
FIXES #332

Fix Powershell Error in _get_names method

---

requirements.txt
wrapanapi/systems/ec2.py

Reduce our import footprint for boto and boto3

[RFR] Narrow boto/boto3 imports for EC2 module

---

wrapanapi/systems/ec2.py

Added list_own_snapshots and delete_snapshot methods
Tested

Added list_own_snapshots and delete_snapshot methods

---

wrapanapi/systems/ec2.py

Reworked sqs_connection to boto3 and added list_queues

---

wrapanapi/systems/container/rhopenshift.py

This happens when openshift project is removed thru api. Openshift <= 3.6 removes pvc/pv earlier than running pods. So, some pods get hung because of that.

[RFR] stopping pods hung if their pvs are removed earlier than pods itself

---

wrapanapi/systems/container/rhopenshift.py

External DB template requires external DB ip and other params. So, this change intends to add ability to pass params to template in order to override default values.
UPD: few more changes to allow using external templates with deploy_template method

[1LP][RFR] adding template params to deploy_template

---

wrapanapi/systems/msazure.py

So there was a problem, similar to this one https://bugzilla.redhat.com/show_bug.cgi?id=1348718 (this one was fixed, when deleting Azure vm from the UI)
When doing `cleanup_on_provider` on Azure using `wrapanapi`, the disks were left and picked up by CFME as private images (which are shown by default). 
Every time `test_vm_capture` ran in the `integration_tests`, new image was "created" resulting in total 130 images in our Azure setup (currently).

[RFR] added disc delete in the vm cleanup

---

wrapanapi/systems/rhevm.py

Adding in methods to get vnic profiles on RHEVM

[RFR] Add in some methods to get the vnic_profiles on system, vm, template

---

wrapanapi/systems/scvmm.py

VMs were only becoming disassociated with SCVMM when the `cleanup_on_provider` or `delete` methods were called. They still existed the filesystem of the host and were therefore taking disk space. Removing the Force kwarg allows them to be properly deleted.
Also adding a `vmid` property and a `host` property.

[RFR] Fix issue with deleting a SCVMM vm by removing Force kwarg

---

wrapanapi/systems/rhevm.py

Some updates to rhevm for 4.2 for template upload support. 
* enhancement to _SharedMethodsMixin, add storage_domains property
* required kwargs for methods that were directly referencing kwarg keys
* enhancement to _SharedMethodsMixin.refresh to allow for kwargs passed to ovirt GET
* Add storage_domain_name optional kwarg to mark_as_template

[1LP][RFR] RHEVM updates for template upload

---

requirements.txt
wrapanapi/systems/openstack.py

Signed-off-by: Nikhil Dhandre <ndhandre@redhat.com>
In-progress

[1LP][RFR] Openstack: swift manger container and obj management

---

wrapanapi/systems/rhevm.py

Adding new method to return disks on RHV env. If needed, can be filtered out with `LOCKED`, `ILLEGAL`, `OK`

[RFR]Adding new method for listing disks on RHV

---

wrapanapi/systems/openstack.py

The when the service name `volume` was used, Cinder couldn't find the image in Glance. Using `volumev3` or `volumev2` causes that different api version will be used and then the Cinder can find the image in Glance fine. 
The change causes wrapanapi to test different versions of volume api and picks the latest one.
There also were some logic problems further in the codepath. `id` parameter must be used to search by id and `id` must be allowed as one of the valid parameters.
This patch is required by https://github.com/ManageIQ/integration_tests/pull/8620

[RFR] Fixes required for test_provision_with_boot_volume

---

wrapanapi/systems/openstack.py
wrapanapi/systems/rhevm.py

Signed-off-by: mnadeem92 <mnadeem@redhat.com>
This PR will create the SharedMethodsMixin class to provide the properties which are common to both OpenstackInstance and OpenstackImage class and also add "creation_time" property to OpenstackImage class. 
This PR will also remove duplicate code from rhevm.py

[1LP][RFR] Adding SharedMethodsMixin class

---

wrapanapi/systems/rhevm.py

include name and sparse kwargs
Change how format/interface enums are fetched

[1LP][RFR] Update rhevm add_disk kwargs

---

wrapanapi/systems/redfish.py

The name property of the Redfish resources such as Physical Systems
or Chassis other than Racks now reflect the method of composing the
name in the ManageIQ's GUI: concatenation of Manufacturer, Name
and, if available, Serial Number in parentheses.
The name of Rack instances is unchanged, i.e., it shows the Id of
the resource. To distinguish the representation from other types
of physical chassis in Redfish, we introduced the `RedfishRack`
class.
Related PR:
* https://github.com/ManageIQ/manageiq-providers-redfish/pull/61

[RFR] Modify the Redfish resources' name

---

wrapanapi/systems/openstack_infra.py
wrapanapi/systems/scvmm.py

Making these methods consistent throughout `wrapanapi`

[RFR] Change list_hosts to list_host

---

wrapanapi/systems/msazure.py

Update imports to follow:
https://github.com/Azure/azure-sdk-for-python/wiki/Direct-access-to-%22models%22-is-deprecated
FIXES #371

[RFR] Update msazure to avoid azure.mgmt.*.models imports where deprecated.

---

wrapanapi/systems/virtualcenter.py

For vsphere, we want to avoid datastore clusters that don't have any datastores.

[RFR]: Add a check to make sure the datastore-cluster has datastores on it

---

wrapanapi/systems/virtualcenter.py

This PR includes two methods:
-  ```create_folder``` for creating vm folder under datacenter
- ```destroy_folder``` to delete the particular vm folder
This functionality is required to automate test case: https://github.com/ManageIQ/integration_tests/pull/9230

[1LP][RFR] Added functinality to create vm folder in virtualcenter

---

wrapanapi/entities/__init__.py
wrapanapi/entities/network.py
wrapanapi/exceptions.py
wrapanapi/systems/ec2.py

Network/NetworkMixin entity added
Also create/list/find/get supporting functions added
Also EC2Vpc entity inheriting from Network added
Tested

[RFR] Added network entity and supporting methods for EC2

---

README.rst

I was working with someone in Satellite team who wanted to use Wrapanapi and it was painful experience for him as he didn't know python. I thought adding installation section would  be a good idea. Please take a look.

[RFR]Adding installation section to enhance README.md

---

wrapanapi/systems/scvmm.py

Apparently `Expand-Archive` is not available on PS version < 5, so we were not able to unzip the archive in SCVMM 2012.
I tested with Windows Server 2012 R2 and Windows Server 2016, working on both.

[RFR] Allow for unzipping archive on Powershell 4

---

wrapanapi/systems/ec2.py

_get_resource method is called from get_"resource_name" and calls find_"resource_name".
As there are many new resources going to be added it's better to have generic _get_resource method so the code is not duplicated for every resource we have.
Tested for all affected resources.

[RFR]_get_resource method implemented for EC2System

---

wrapanapi/systems/container/rhopenshift.py

there have been changes in openshift cloudforms streams. wrapanapi has to be updated accordingly

[RFR] update openshift tags and etc

---

wrapanapi/entities/__init__.py
wrapanapi/entities/network.py
wrapanapi/entities/volume.py
wrapanapi/exceptions.py
wrapanapi/systems/ec2.py

Added EC2Volume entity needed for targeted refresh tests in cfme_tests.

[RFR] EC2Volume entity added

---

wrapanapi/systems/ec2.py

We need to list aws regions.
With verbose=True set it lists regions in format needed for comparison in CFME UI 'US West (N. California)'.
Otherwise it lists regions in format 'us-west-1'.

[RFR]AWS region list method

---

wrapanapi/systems/ec2.py

Added create_stack method for creating CloudFormation stack from EC2System.
Also added check whether status of stack is "ACTIVE".

[RFR]EC2 create_stack method

---

wrapanapi/systems/ec2.py

When AWSConfig_topic is deleted and then recreated CloudWatch rule targets are assigned to topics, but there is bug in AWS and targets are not working correctly so we need to modify targets when topic is recreated.
It can fail on multiple phases so there is try/except for whole method.

[RFR]Added set_sns_topic_target_for_all_cw_rules method

---

wrapanapi/systems/virtualcenter.py

I need this method for my test in PR #ManageIQ/integration_tests/pull/9901 to work. This method unregisters VM from VMware inventory.

Adding new method to unregister vm from vmware

---

wrapanapi/systems/ec2.py

Added functions to import snapshots so we can import snapshots instead of images to AWS EC2.

[RFR]Added ec2 snapshot import functions

---

wrapanapi/systems/ec2.py

EC2: Remove all unused Volumes, IPs and NICs from a region

---

wrapanapi/systems/google.py

Functionality to allow users to pass the projects to list the templates/images.
Corresponding robottelo PR: https://github.com/SatelliteQE/robottelo/pull/10765/files

Adding functionality to pass projects while listing templates/images

---

pyproject.toml

Unpinning the podman dependency to be greater than 5.0.0

Podman version pinning removed

---

README.rst

Readme is updated for podman support

Podman support is added
